  public Exception getCaughtException() {
    return _caughtException;
  }
